name: Unit test, log code coverage, and build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and build on Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn test # generates coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - run: yarn run build
